-- فروشگاه معیلی — این فایل کامل idempotent است و روی پروژه‌ی قبلی هم بدون آسیب به داده‌ها قابل اجراست.
-- کل فایل را در Supabase SQL Editor اجرا کنید.

create extension if not exists pgcrypto;

-- ============ جدول‌های پایه (از قبل موجودند؛ بدون تغییر ساختار) ============
create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  description text default '',
  consumer_price bigint not null check (consumer_price >= 0),
  store_price bigint not null check (store_price >= 0 and store_price <= consumer_price),
  stock integer not null default 0 check (stock >= 0),
  unit text not null default 'عدد',
  image_url text default '',
  is_popular boolean not null default false,
  is_new boolean not null default true,
  is_visible boolean not null default true,
  store_price_enabled boolean not null default true,
  show_discount_badge boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number text unique not null,
  customer_name text not null,
  phone text not null,
  address text not null,
  note text default '',
  subtotal bigint not null default 0,
  discount_total bigint not null default 0,
  final_total bigint not null default 0,
  status text not null default 'ثبت شده'
    check(status in ('ثبت شده','تأیید شده','آماده ارسال','در حال ارسال','تحویل شده','لغو شده')),
  created_at timestamptz not null default now()
);

-- شماره فاکتورهای کوتاه و ساده: ۱۰۲۴۰، ۱۰۲۴۱، ۱۰۲۴۲، ...
create sequence if not exists public.invoice_number_seq start with 10240;

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id uuid references public.products(id) on delete set null,
  product_name text not null,
  quantity integer not null check(quantity > 0),
  unit_price bigint not null,
  consumer_price bigint not null,
  discount_percent integer not null default 0,
  total bigint not null
);

-- ============ سازگاری با نسخه‌های قبلی ============
alter table public.orders add column if not exists user_id uuid references auth.users(id);
alter table public.products add column if not exists is_visible boolean not null default true;
alter table public.products add column if not exists store_price_enabled boolean not null default true;
alter table public.products add column if not exists show_discount_badge boolean not null default true;
alter table public.orders add column if not exists delivery_method text not null default 'pickup';
alter table public.orders add column if not exists shipping_cost bigint not null default 0;

create index if not exists orders_user_id_idx on public.orders(user_id);

create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  phone text not null default '',
  address text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists profiles_phone_idx on public.profiles(phone);

create table if not exists public.site_settings (
  key text primary key,
  value text not null default '',
  updated_at timestamptz not null default now()
);
insert into public.site_settings(key,value) values
 ('banner_url',''),('logo_url',''),('shipping_enabled','true'),('shipping_cost','0')
on conflict(key) do nothing;

-- ============ جدید: دسته‌بندی محصولات (رنگی، چندتایی برای هر محصول) ============
create table if not exists public.categories (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  color text not null default '#2E6B3E',
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.product_categories (
  product_id uuid not null references public.products(id) on delete cascade,
  category_id uuid not null references public.categories(id) on delete cascade,
  primary key (product_id, category_id)
);

-- ============ فعال‌سازی RLS ============
alter table public.products enable row level security;
alter table public.admins enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.categories enable row level security;
alter table public.product_categories enable row level security;
alter table public.profiles enable row level security;
alter table public.site_settings enable row level security;

-- محصولات و دسته‌بندی‌ها برای همه قابل مشاهده‌اند؛ فقط مدیر تغییر می‌دهد.
drop policy if exists "public read products" on public.products;
create policy "public read products" on public.products for select using (true);
drop policy if exists "admins manage products" on public.products;
create policy "admins manage products" on public.products for all to authenticated
using (exists(select 1 from public.admins a where a.user_id=auth.uid()))
with check (exists(select 1 from public.admins a where a.user_id=auth.uid()));

drop policy if exists "public read categories" on public.categories;
create policy "public read categories" on public.categories for select using (true);
drop policy if exists "admins manage categories" on public.categories;
create policy "admins manage categories" on public.categories for all to authenticated
using (exists(select 1 from public.admins a where a.user_id=auth.uid()))
with check (exists(select 1 from public.admins a where a.user_id=auth.uid()));

drop policy if exists "public read product_categories" on public.product_categories;
create policy "public read product_categories" on public.product_categories for select using (true);
drop policy if exists "admins manage product_categories" on public.product_categories;
create policy "admins manage product_categories" on public.product_categories for all to authenticated
using (exists(select 1 from public.admins a where a.user_id=auth.uid()))
with check (exists(select 1 from public.admins a where a.user_id=auth.uid()));

drop policy if exists "admins read admins" on public.admins;
create policy "admins read admins" on public.admins for select to authenticated
using (user_id=auth.uid());

drop policy if exists "admins read profiles" on public.profiles;
create policy "admins read profiles" on public.profiles for select to authenticated
using (exists(select 1 from public.admins a where a.user_id=auth.uid()));

drop policy if exists "public read site settings" on public.site_settings;
create policy "public read site settings" on public.site_settings for select using (true);
drop policy if exists "admins manage site settings" on public.site_settings;
create policy "admins manage site settings" on public.site_settings for all to authenticated
using (exists(select 1 from public.admins a where a.user_id=auth.uid()))
with check (exists(select 1 from public.admins a where a.user_id=auth.uid()));

-- سفارش‌ها: فقط مدیر از جدول مستقیم سفارش‌ها دسترسی مدیریتی دارد؛ مشتری از RPC شماره پیگیری استفاده می‌کند.
drop policy if exists "admins manage orders" on public.orders;
create policy "admins manage orders" on public.orders for all to authenticated
using (exists(select 1 from public.admins a where a.user_id=auth.uid()))
with check (exists(select 1 from public.admins a where a.user_id=auth.uid()));


drop policy if exists "admins read order items" on public.order_items;
create policy "admins read order items" on public.order_items for select to authenticated
using (exists(select 1 from public.admins a where a.user_id=auth.uid()));


-- ============ ثبت سفارش بدون حساب مشتری ============
-- مشتری فقط نام، موبایل، آدرس و شماره پیگیری دارد؛ نیازی به Authentication ندارد.
-- هماهنگ‌کردن شماره‌ساز با سفارش‌های قبلی؛ اولین شماره در صورت خالی بودن ۱۰۲۴۰ است.
do $$
begin
  perform setval('public.invoice_number_seq', greatest(
    10239,
    coalesce((select max(order_number::bigint) from public.orders where order_number ~ '^[0-9]+$'), 10239)
  ), true);
end $$;

drop function if exists public.create_order(text,text,text,text,jsonb,text);
create or replace function public.create_order(
  customer_name text,
  phone text,
  address text,
  note text default '',
  items jsonb default '[]'::jsonb,
  delivery_method text default 'pickup'
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order_id uuid;
  v_order_number text;
  v_subtotal bigint := 0;
  v_final bigint := 0;
  v_item jsonb;
  v_product public.products%rowtype;
  v_qty integer;
  v_discount bigint;
  v_shipping bigint := 0;
begin
  if delivery_method not in ('pickup','delivery') then raise exception 'روش دریافت نامعتبر است'; end if;
  if delivery_method='delivery' then
    if coalesce((select value from public.site_settings where key='shipping_enabled'),'true') <> 'true' then raise exception 'ارسال در حال حاضر غیرفعال است'; end if;
    v_shipping := coalesce((select nullif(value,'')::bigint from public.site_settings where key='shipping_cost'),0);
  end if;
  if length(trim(customer_name)) < 2 then raise exception 'نام مشتری نامعتبر است'; end if;
  if regexp_replace(phone,'[^0-9]','','g') !~ '^09[0-9]{9}$' then raise exception 'شماره موبایل باید دقیقاً ۱۱ رقم و با 09 شروع شود'; end if;
  if length(trim(address)) < 5 then raise exception 'آدرس نامعتبر است'; end if;
  if jsonb_array_length(items)=0 then raise exception 'سبد خرید خالی است'; end if;

  for v_item in select * from jsonb_array_elements(items)
  loop
    select * into v_product from public.products where id=(v_item->>'product_id')::uuid for update;
    if not found then raise exception 'محصول پیدا نشد'; end if;
    if not v_product.is_visible then raise exception 'این محصول در حال حاضر قابل سفارش نیست'; end if;
    v_qty := greatest(0,(v_item->>'quantity')::integer);
    if v_qty < 1 then raise exception 'تعداد محصول نامعتبر است'; end if;
    if v_qty > v_product.stock then raise exception 'stock: موجودی % کافی نیست',v_product.name; end if;
    v_subtotal := v_subtotal + v_product.consumer_price*v_qty;
    v_final := v_final + (case when v_product.store_price_enabled then v_product.store_price else v_product.consumer_price end)*v_qty;
  end loop;
  v_final := v_final + v_shipping;

  v_order_number := nextval('public.invoice_number_seq')::text;
  while exists(select 1 from public.orders where order_number=v_order_number) loop
    v_order_number := nextval('public.invoice_number_seq')::text;
  end loop;

  insert into public.orders(order_number,customer_name,phone,address,note,subtotal,discount_total,final_total,delivery_method,shipping_cost)
  values(v_order_number,trim(customer_name),regexp_replace(phone,'[^0-9]','','g'),trim(address),coalesce(note,''),v_subtotal,v_subtotal-(v_final-v_shipping),v_final,delivery_method,v_shipping)
  returning id into v_order_id;

  for v_item in select * from jsonb_array_elements(items)
  loop
    select * into v_product from public.products where id=(v_item->>'product_id')::uuid for update;
    v_qty := (v_item->>'quantity')::integer;
    update public.products set stock=stock-v_qty,updated_at=now() where id=v_product.id;
    v_discount := case when v_product.consumer_price>0 then round((v_product.consumer_price-v_product.store_price)*100.0/v_product.consumer_price) else 0 end;
    insert into public.order_items(order_id,product_id,product_name,quantity,unit_price,consumer_price,discount_percent,total)
    values(v_order_id,v_product.id,v_product.name,v_qty,case when v_product.store_price_enabled then v_product.store_price else v_product.consumer_price end,v_product.consumer_price,case when v_product.store_price_enabled then v_discount else 0 end,(case when v_product.store_price_enabled then v_product.store_price else v_product.consumer_price end)*v_qty);
  end loop;

  return jsonb_build_object('order_number',v_order_number,'order_id',v_order_id);
end $$;

-- پیگیری عمومی فقط با شماره پیگیری تصادفی سفارش
-- بازیابی فاکتور: مشتری باید هم شماره موبایل و هم شماره فاکتور را وارد کند.
-- پس از تأیید هر دو، تمام فاکتورهای همان شماره موبایل نمایش داده می‌شود.
drop function if exists public.get_order_by_number(text);
drop function if exists public.lookup_orders_by_phone_and_invoice(text,text);
create or replace function public.lookup_orders_by_phone_and_invoice(p_phone text,p_order_number text)
returns table(
  order_number text,customer_name text,phone text,address text,note text,
  subtotal bigint,discount_total bigint,final_total bigint,delivery_method text,shipping_cost bigint,status text,created_at timestamptz,items jsonb
)
language sql
security definer
set search_path=public
as $$
  select o.order_number,o.customer_name,o.phone,o.address,o.note,o.subtotal,o.discount_total,o.final_total,o.delivery_method,o.shipping_cost,o.status,o.created_at,
  coalesce((select jsonb_agg(jsonb_build_object(
    'product_name',i.product_name,'quantity',i.quantity,'unit_price',i.unit_price,
    'store_price',i.unit_price,'consumer_price',i.consumer_price,'discount_percent',i.discount_percent,'total',i.total
  ) order by i.id) from public.order_items i where i.order_id=o.id),'[]'::jsonb)
  from public.orders o
  where o.phone=regexp_replace(p_phone,'[^0-9]','','g')
    and exists(
      select 1 from public.orders check_order
      where check_order.phone=regexp_replace(p_phone,'[^0-9]','','g')
        and check_order.order_number=regexp_replace(p_order_number,'[^0-9]','','g')
    )
  order by o.created_at desc;
$$;

grant execute on function public.create_order(text,text,text,text,jsonb,text) to anon, authenticated;
grant execute on function public.lookup_orders_by_phone_and_invoice(text,text) to anon, authenticated;
drop function if exists public.get_my_orders();
drop function if exists public.lookup_orders(text);

-- Storage bucket برای عکس محصولات
insert into storage.buckets (id,name,public)
values ('product-images','product-images',true)
on conflict (id) do update set public=true;

drop policy if exists "public view product images" on storage.objects;
create policy "public view product images" on storage.objects for select
using (bucket_id='product-images');

drop policy if exists "admins upload product images" on storage.objects;
create policy "admins upload product images" on storage.objects for insert to authenticated
with check (
  bucket_id='product-images'
  and exists(select 1 from public.admins a where a.user_id=auth.uid())
);

drop policy if exists "admins update product images" on storage.objects;
create policy "admins update product images" on storage.objects for update to authenticated
using (bucket_id='product-images' and exists(select 1 from public.admins a where a.user_id=auth.uid()))
with check (bucket_id='product-images' and exists(select 1 from public.admins a where a.user_id=auth.uid()));

drop policy if exists "admins delete product images" on storage.objects;
create policy "admins delete product images" on storage.objects for delete to authenticated
using (bucket_id='product-images' and exists(select 1 from public.admins a where a.user_id=auth.uid()));

-- بعد از ساخت کاربر مدیر در Authentication، UUID او را جایگزین کنید:
-- insert into public.admins(user_id) values ('7c3622e2-7f5a-41f1-8406-b671e2e9b446');

-- مشتری‌ها دیگر حساب کاربری یا رمز عبور ندارند؛ Authentication فقط برای مدیر سایت استفاده می‌شود.


-- گزارش مشتریان برای پنل مدیریت؛ بدون نیاز به حساب مشتری
drop function if exists public.get_all_customers();
create or replace function public.get_all_customers()
returns table(customer_name text,phone text,address text,order_count bigint,last_order_at timestamptz)
language sql security definer set search_path=public
as $$
 select o.customer_name,o.phone,max(o.address) as address,count(*)::bigint,max(o.created_at) as last_order_at
 from public.orders o
 where exists(select 1 from public.admins a where a.user_id=auth.uid())
 group by o.customer_name,o.phone
 order by max(o.created_at) desc;
$$;
grant execute on function public.get_all_customers() to authenticated;
