-- فروشگاه معیلی — این فایل کامل idempotent است و روی پروژه‌ی قبلی هم بدون آسیب به داده‌ها قابل اجراست.
-- کل فایل را در Supabase SQL Editor اجرا کنید.

create extension if not exists pgcrypto;

-- ============ جدول‌های پایه (از قبل موجودند؛ بدون تغییر ساختار) ============
create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  description text default '',
  consumer_price bigint not null check (consumer_price >= 0),
  store_price bigint not null check (store_price >= 0 and store_price <= consumer_price),
  stock integer not null default 0 check (stock >= 0),
  unit text not null default 'عدد',
  image_url text default '',
  is_popular boolean not null default false,
  is_new boolean not null default true,
  is_visible boolean not null default true,
  store_price_enabled boolean not null default true,
  show_discount_badge boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number text unique not null,
  customer_name text not null,
  phone text not null,
  address text not null,
  note text default '',
  subtotal bigint not null default 0,
  discount_total bigint not null default 0,
  final_total bigint not null default 0,
  status text not null default 'ثبت شده'
    check(status in ('ثبت شده','تأیید شده','آماده ارسال','در حال ارسال','تحویل شده','لغو شده')),
  created_at timestamptz not null default now()
);

-- شماره فاکتورهای کوتاه و ساده: ۱۰۲۴۰، ۱۰۲۴۱، ۱۰۲۴۲، ...
create sequence if not exists public.invoice_number_seq start with 10240;

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id uuid references public.products(id) on delete set null,
  product_name text not null,
  quantity integer not null check(quantity > 0),
  unit_price bigint not null,
  consumer_price bigint not null,
  discount_percent integer not null default 0,
  total bigint not null
);

-- ============ سازگاری با نسخه‌های قبلی ============
alter table public.orders add column if not exists user_id uuid references auth.users(id);
alter table public.orders add column if not exists stock_deducted boolean not null default false;
alter table public.orders drop constraint if exists orders_status_check;
alter table public.orders add constraint orders_status_check check(status in ('ثبت شده','در انتظار تأیید','تأیید شده','آماده ارسال','در حال ارسال','تحویل شده','لغو شده'));

alter table public.products add column if not exists sort_order integer;
-- ترتیب اولیه محصولات قدیمی را بر اساس زمان ایجاد می‌سازیم؛ بعداً از پنل مدیریت قابل جابه‌جایی است.
with ranked as (
  select id, row_number() over(order by created_at asc, id asc) as rn from public.products
)
update public.products p set sort_order=r.rn from ranked r where p.id=r.id and p.sort_order is null;
alter table public.products alter column sort_order set default 1;
alter table public.products add column if not exists is_visible boolean not null default true;
alter table public.products add column if not exists store_price_enabled boolean not null default true;
alter table public.products add column if not exists show_discount_badge boolean not null default true;
alter table public.orders add column if not exists delivery_method text not null default 'pickup';
alter table public.orders add column if not exists shipping_cost bigint not null default 0;

create index if not exists orders_user_id_idx on public.orders(user_id);

create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  phone text not null default '',
  address text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists profiles_phone_idx on public.profiles(phone);

create table if not exists public.site_settings (
  key text primary key,
  value text not null default '',
  updated_at timestamptz not null default now()
);
insert into public.site_settings(key,value) values
 ('banner_url',''),('logo_url',''),('shipping_enabled','true'),('shipping_cost','0'),('minimum_order_amount','0'),('high_value_order_threshold','5000000')
on conflict(key) do nothing;

-- ============ جدید: دسته‌بندی محصولات (رنگی، چندتایی برای هر محصول) ============
create table if not exists public.categories (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  color text not null default '#2E6B3E',
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.product_categories (
  product_id uuid not null references public.products(id) on delete cascade,
  category_id uuid not null references public.categories(id) on delete cascade,
  primary key (product_id, category_id)
);

-- ============ فعال‌سازی RLS ============
alter table public.products enable row level security;
alter table public.admins enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.categories enable row level security;
alter table public.product_categories enable row level security;
alter table public.profiles enable row level security;
alter table public.site_settings enable row level security;

-- محصولات و دسته‌بندی‌ها برای همه قابل مشاهده‌اند؛ فقط مدیر تغییر می‌دهد.
drop policy if exists "public read products" on public.products;
create policy "public read products" on public.products for select using (true);
drop policy if exists "admins manage products" on public.products;
create policy "admins manage products" on public.products for all to authenticated
using (exists(select 1 from public.admins a where a.user_id=auth.uid()))
with check (exists(select 1 from public.admins a where a.user_id=auth.uid()));

drop policy if exists "public read categories" on public.categories;
create policy "public read categories" on public.categories for select using (true);
drop policy if exists "admins manage categories" on public.categories;
create policy "admins manage categories" on public.categories for all to authenticated
using (exists(select 1 from public.admins a where a.user_id=auth.uid()))
with check (exists(select 1 from public.admins a where a.user_id=auth.uid()));

drop policy if exists "public read product_categories" on public.product_categories;
create policy "public read product_categories" on public.product_categories for select using (true);
drop policy if exists "admins manage product_categories" on public.product_categories;
create policy "admins manage product_categories" on public.product_categories for all to authenticated
using (exists(select 1 from public.admins a where a.user_id=auth.uid()))
with check (exists(select 1 from public.admins a where a.user_id=auth.uid()));

drop policy if exists "admins read admins" on public.admins;
create policy "admins read admins" on public.admins for select to authenticated
using (user_id=auth.uid());

drop policy if exists "admins read profiles" on public.profiles;
create policy "admins read profiles" on public.profiles for select to authenticated
using (exists(select 1 from public.admins a where a.user_id=auth.uid()));

drop policy if exists "public read site settings" on public.site_settings;
create policy "public read site settings" on public.site_settings for select using (true);
drop policy if exists "admins manage site settings" on public.site_settings;
create policy "admins manage site settings" on public.site_settings for all to authenticated
using (exists(select 1 from public.admins a where a.user_id=auth.uid()))
with check (exists(select 1 from public.admins a where a.user_id=auth.uid()));

-- سفارش‌ها: فقط مدیر از جدول مستقیم سفارش‌ها دسترسی مدیریتی دارد؛ مشتری از RPC شماره پیگیری استفاده می‌کند.
drop policy if exists "admins manage orders" on public.orders;
drop policy if exists "admins read orders" on public.orders;
drop policy if exists "admins delete orders" on public.orders;
create policy "admins read orders" on public.orders for select to authenticated
using (exists(select 1 from public.admins a where a.user_id=auth.uid()));
create policy "admins delete orders" on public.orders for delete to authenticated
using (exists(select 1 from public.admins a where a.user_id=auth.uid()));


drop policy if exists "admins read order items" on public.order_items;
create policy "admins read order items" on public.order_items for select to authenticated
using (exists(select 1 from public.admins a where a.user_id=auth.uid()));


-- ============ ثبت سفارش بدون حساب مشتری ============
-- مشتری فقط نام، موبایل، آدرس و شماره پیگیری دارد؛ نیازی به Authentication ندارد.
-- هماهنگ‌کردن شماره‌ساز با سفارش‌های قبلی؛ اولین شماره در صورت خالی بودن ۱۰۲۴۰ است.
do $$
begin
  perform setval('public.invoice_number_seq', greatest(
    10239,
    coalesce((select max(order_number::bigint) from public.orders where order_number ~ '^[0-9]+$'), 10239)
  ), true);
end $$;

drop function if exists public.create_order(text,text,text,text,jsonb,text);
create or replace function public.create_order(
  customer_name text,
  phone text,
  address text,
  note text default '',
  items jsonb default '[]'::jsonb,
  delivery_method text default 'pickup'
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order_id uuid;
  v_order_number text;
  v_subtotal bigint := 0;
  v_final bigint := 0;
  v_item jsonb;
  v_product public.products%rowtype;
  v_qty integer;
  v_discount bigint;
  v_shipping bigint := 0;
  v_minimum_order bigint := 0;
  v_threshold bigint := 5000000;
  v_status text := 'ثبت شده';
  v_stock_deducted boolean := true;
begin
  if delivery_method not in ('pickup','delivery') then raise exception 'روش دریافت نامعتبر است'; end if;
  if delivery_method='delivery' then
    if coalesce((select value from public.site_settings where key='shipping_enabled'),'true') <> 'true' then raise exception 'ارسال در حال حاضر غیرفعال است'; end if;
    v_shipping := coalesce((select nullif(value,'')::bigint from public.site_settings where key='shipping_cost'),0);
  end if;

  customer_name := regexp_replace(trim(customer_name), '\s+', ' ', 'g');
  phone := regexp_replace(phone,'[^0-9]','','g');

  if length(customer_name) < 3 or length(customer_name) > 60
     or customer_name !~ '[آ-یA-Za-z]'
     or customer_name !~ '[اآییووهئAEIOUaeiou]'
     or customer_name ~ '[0-9_@#$%&*+=<>|~`^{}[\]\\/]'
     or customer_name ~ '(.)\1\1'
  then raise exception 'نام و نام‌خانوادگی واردشده معتبر نیست'; end if;

  if phone !~ '^09(0|1|2|3|9)[0-9]{8}$'
     or phone ~ '^0([0-9])\1{9}$'
     or phone ~ '^09[0-9]([0-9])\1{7}$'
  then raise exception 'شماره موبایل معتبر نیست؛ شماره‌های ساختگی یا تکراری پذیرفته نمی‌شوند'; end if;

  if length(trim(address)) < 5 then raise exception 'آدرس نامعتبر است'; end if;
  if jsonb_array_length(items)=0 then raise exception 'سبد خرید خالی است'; end if;
  if jsonb_array_length(items) <> (select count(distinct x->>'product_id') from jsonb_array_elements(items) x) then
    raise exception 'سبد خرید نامعتبر است';
  end if;

  -- ابتدا تمام اقلام را اعتبارسنجی و قیمت نهایی را از دیتابیس محاسبه می‌کنیم.
  -- FOR UPDATE باعث می‌شود دو سفارش همزمان نتوانند موجودی یک محصول را به‌صورت نادرست مصرف کنند.
  for v_item in select * from jsonb_array_elements(items)
  loop
    select * into v_product from public.products where id=(v_item->>'product_id')::uuid for update;
    if not found then raise exception 'محصول پیدا نشد'; end if;
    if not v_product.is_visible then raise exception 'این محصول در حال حاضر قابل سفارش نیست'; end if;
    v_qty := (v_item->>'quantity')::integer;
    if v_qty < 1 then raise exception 'تعداد محصول نامعتبر است'; end if;
    if v_qty > v_product.stock then raise exception 'stock: موجودی % کافی نیست',v_product.name; end if;
    v_subtotal := v_subtotal + v_product.consumer_price*v_qty;
    v_final := v_final + (case when v_product.store_price_enabled then v_product.store_price else v_product.consumer_price end)*v_qty;
  end loop;

  v_minimum_order := coalesce((select nullif(value,'')::bigint from public.site_settings where key='minimum_order_amount'),0);
  if v_minimum_order > 0 and v_final < v_minimum_order then
    raise exception 'حداقل مبلغ سفارش % تومان است', v_minimum_order;
  end if;

  v_threshold := coalesce((select nullif(value,'')::bigint from public.site_settings where key='high_value_order_threshold'),5000000);
  if v_threshold > 0 and (v_final + v_shipping) > v_threshold then
    v_status := 'در انتظار تأیید';
    v_stock_deducted := false;
  end if;
  v_final := v_final + v_shipping;

  v_order_number := nextval('public.invoice_number_seq')::text;
  while exists(select 1 from public.orders where order_number=v_order_number) loop
    v_order_number := nextval('public.invoice_number_seq')::text;
  end loop;

  insert into public.orders(order_number,customer_name,phone,address,note,subtotal,discount_total,final_total,delivery_method,shipping_cost,status,stock_deducted)
  values(v_order_number,customer_name,phone,trim(address),coalesce(note,''),v_subtotal,v_subtotal-(v_final-v_shipping),v_final,delivery_method,v_shipping,v_status,v_stock_deducted)
  returning id into v_order_id;

  -- فقط سفارش‌های عادی موجودی را همین‌جا کم می‌کنند.
  if v_stock_deducted then
    for v_item in select * from jsonb_array_elements(items)
    loop
      select * into v_product from public.products where id=(v_item->>'product_id')::uuid for update;
      v_qty := (v_item->>'quantity')::integer;
      if v_qty > v_product.stock then
        raise exception 'stock: موجودی % کافی نیست',v_product.name;
      end if;
      update public.products set stock=stock-v_qty,updated_at=now() where id=v_product.id;
      v_discount := case when v_product.consumer_price>0 then round((v_product.consumer_price-v_product.store_price)*100.0/v_product.consumer_price) else 0 end;
      insert into public.order_items(order_id,product_id,product_name,quantity,unit_price,consumer_price,discount_percent,total)
      values(v_order_id,v_product.id,v_product.name,v_qty,case when v_product.store_price_enabled then v_product.store_price else v_product.consumer_price end,v_product.consumer_price,case when v_product.store_price_enabled then v_discount else 0 end,(case when v_product.store_price_enabled then v_product.store_price else v_product.consumer_price end)*v_qty);
    end loop;
  else
    for v_item in select * from jsonb_array_elements(items)
    loop
      select * into v_product from public.products where id=(v_item->>'product_id')::uuid for update;
      v_qty := (v_item->>'quantity')::integer;
      v_discount := case when v_product.consumer_price>0 then round((v_product.consumer_price-v_product.store_price)*100.0/v_product.consumer_price) else 0 end;
      insert into public.order_items(order_id,product_id,product_name,quantity,unit_price,consumer_price,discount_percent,total)
      values(v_order_id,v_product.id,v_product.name,v_qty,case when v_product.store_price_enabled then v_product.store_price else v_product.consumer_price end,v_product.consumer_price,case when v_product.store_price_enabled then v_discount else 0 end,(case when v_product.store_price_enabled then v_product.store_price else v_product.consumer_price end)*v_qty);
    end loop;
  end if;

  return jsonb_build_object('order_number',v_order_number,'order_id',v_order_id,'status',v_status,'requires_approval',not v_stock_deducted);
end $$;

-- پیگیری عمومی فقط با شماره پیگیری تصادفی سفارش
-- بازیابی فاکتور: مشتری باید هم شماره موبایل و هم شماره فاکتور را وارد کند.
-- پس از تأیید هر دو، تمام فاکتورهای همان شماره موبایل نمایش داده می‌شود.
drop function if exists public.get_order_by_number(text);
drop function if exists public.lookup_orders_by_phone_and_invoice(text,text);
create or replace function public.lookup_orders_by_phone_and_invoice(p_phone text,p_order_number text)
returns table(
  order_number text,customer_name text,phone text,address text,note text,
  subtotal bigint,discount_total bigint,final_total bigint,delivery_method text,shipping_cost bigint,status text,created_at timestamptz,items jsonb
)
language sql
security definer
set search_path=public
as $$
  select o.order_number,o.customer_name,o.phone,o.address,o.note,o.subtotal,o.discount_total,o.final_total,o.delivery_method,o.shipping_cost,o.status,o.created_at,
  coalesce((select jsonb_agg(jsonb_build_object(
    'product_name',i.product_name,'quantity',i.quantity,'unit_price',i.unit_price,
    'store_price',i.unit_price,'consumer_price',i.consumer_price,'discount_percent',i.discount_percent,'total',i.total
  ) order by i.id) from public.order_items i where i.order_id=o.id),'[]'::jsonb)
  from public.orders o
  where o.phone=regexp_replace(p_phone,'[^0-9]','','g')
    and exists(
      select 1 from public.orders check_order
      where check_order.phone=regexp_replace(p_phone,'[^0-9]','','g')
        and check_order.order_number=regexp_replace(p_order_number,'[^0-9]','','g')
    )
  order by o.created_at desc;
$$;

grant execute on function public.create_order(text,text,text,text,jsonb,text) to anon, authenticated;
grant execute on function public.lookup_orders_by_phone_and_invoice(text,text) to anon, authenticated;
drop function if exists public.get_my_orders();
drop function if exists public.lookup_orders(text);

-- Storage bucket برای عکس محصولات
insert into storage.buckets (id,name,public)
values ('product-images','product-images',true)
on conflict (id) do update set public=true;

drop policy if exists "public view product images" on storage.objects;
create policy "public view product images" on storage.objects for select
using (bucket_id='product-images');

drop policy if exists "admins upload product images" on storage.objects;
create policy "admins upload product images" on storage.objects for insert to authenticated
with check (
  bucket_id='product-images'
  and exists(select 1 from public.admins a where a.user_id=auth.uid())
);

drop policy if exists "admins update product images" on storage.objects;
create policy "admins update product images" on storage.objects for update to authenticated
using (bucket_id='product-images' and exists(select 1 from public.admins a where a.user_id=auth.uid()))
with check (bucket_id='product-images' and exists(select 1 from public.admins a where a.user_id=auth.uid()));

drop policy if exists "admins delete product images" on storage.objects;
create policy "admins delete product images" on storage.objects for delete to authenticated
using (bucket_id='product-images' and exists(select 1 from public.admins a where a.user_id=auth.uid()));

-- بعد از ساخت کاربر مدیر در Authentication، UUID او را جایگزین کنید:
-- insert into public.admins(user_id) values ('7c3622e2-7f5a-41f1-8406-b671e2e9b446');

-- مشتری‌ها دیگر حساب کاربری یا رمز عبور ندارند؛ Authentication فقط برای مدیر سایت استفاده می‌شود.



-- ============ مدیریت امن وضعیت سفارش و موجودی ============
drop function if exists public.update_order_status(uuid,text);
create or replace function public.update_order_status(p_order_id uuid,p_status text)
returns boolean
language plpgsql security definer set search_path=public
as $$
declare
  v_order public.orders%rowtype;
  v_item public.order_items%rowtype;
  v_product public.products%rowtype;
begin
  if not exists(select 1 from public.admins a where a.user_id=auth.uid()) then raise exception 'not authorized'; end if;
  if p_status not in ('ثبت شده','در انتظار تأیید','تأیید شده','آماده ارسال','در حال ارسال','تحویل شده','لغو شده') then
    raise exception 'وضعیت سفارش نامعتبر است';
  end if;

  select * into v_order from public.orders where id=p_order_id for update;
  if not found then raise exception 'سفارش پیدا نشد'; end if;

  if p_status='تأیید شده' and v_order.status='در انتظار تأیید' then
    for v_item in select * from public.order_items where order_id=p_order_id order by id
    loop
      if v_item.product_id is null then raise exception 'محصول سفارش دیگر وجود ندارد: %',v_item.product_name; end if;
      select * into v_product from public.products where id=v_item.product_id for update;
      if not found then raise exception 'محصول سفارش دیگر وجود ندارد: %',v_item.product_name; end if;
      if v_product.stock < v_item.quantity then
        raise exception 'موجودی % کافی نیست؛ سفارش تأیید نشد',v_product.name;
      end if;
    end loop;

    for v_item in select * from public.order_items where order_id=p_order_id order by id
    loop
      update public.products set stock=stock-v_item.quantity,updated_at=now() where id=v_item.product_id;
    end loop;
    update public.orders set stock_deducted=true,status='تأیید شده' where id=p_order_id;
    return true;
  end if;

  if p_status='لغو شده' and v_order.stock_deducted then
    for v_item in select * from public.order_items where order_id=p_order_id
    loop
      if v_item.product_id is not null then
        update public.products set stock=stock+v_item.quantity,updated_at=now() where id=v_item.product_id;
      end if;
    end loop;
    update public.orders set stock_deducted=false,status='لغو شده' where id=p_order_id;
    return true;
  end if;

  update public.orders set status=p_status where id=p_order_id;
  return true;
end $$;
grant execute on function public.update_order_status(uuid,text) to authenticated;

drop function if exists public.delete_order_and_restore_stock(uuid);
create or replace function public.delete_order_and_restore_stock(p_order_id uuid)
returns boolean
language plpgsql security definer set search_path=public
as $$
declare
  v_order public.orders%rowtype;
  v_item public.order_items%rowtype;
begin
  if not exists(select 1 from public.admins a where a.user_id=auth.uid()) then raise exception 'not authorized'; end if;
  select * into v_order from public.orders where id=p_order_id for update;
  if not found then raise exception 'سفارش پیدا نشد'; end if;

  if v_order.stock_deducted then
    for v_item in select * from public.order_items where order_id=p_order_id
    loop
      if v_item.product_id is not null then
        update public.products set stock=stock+v_item.quantity,updated_at=now() where id=v_item.product_id;
      end if;
    end loop;
  end if;

  delete from public.orders where id=p_order_id;
  return true;
end $$;
grant execute on function public.delete_order_and_restore_stock(uuid) to authenticated;

-- گزارش مشتریان برای پنل مدیریت؛ بدون نیاز به حساب مشتری
drop function if exists public.get_all_customers();
create or replace function public.get_all_customers()
returns table(customer_name text,phone text,address text,order_count bigint,last_order_at timestamptz)
language sql security definer set search_path=public
as $$
 select o.customer_name,o.phone,max(o.address) as address,count(*)::bigint,max(o.created_at) as last_order_at
 from public.orders o
 where exists(select 1 from public.admins a where a.user_id=auth.uid())
 group by o.customer_name,o.phone
 order by max(o.created_at) desc;
$$;
grant execute on function public.get_all_customers() to authenticated;

-- حذف کامل مشتری توسط مدیر: چون مشتری جدول حساب جداگانه ندارد، مشتری بر اساس شماره موبایل از سفارش‌ها تشکیل می‌شود.
drop function if exists public.delete_customer_by_phone(text);
create or replace function public.delete_customer_by_phone(p_phone text)
returns integer
language plpgsql security definer set search_path=public
as $$
declare
  v_count integer;
  v_order public.orders%rowtype;
  v_item public.order_items%rowtype;
begin
  if not exists(select 1 from public.admins a where a.user_id=auth.uid()) then raise exception 'not authorized'; end if;

  for v_order in select * from public.orders where phone=regexp_replace(p_phone,'[^0-9]','','g') for update
  loop
    if v_order.stock_deducted then
      for v_item in select * from public.order_items where order_id=v_order.id
      loop
        if v_item.product_id is not null then
          update public.products set stock=stock+v_item.quantity,updated_at=now() where id=v_item.product_id;
        end if;
      end loop;
    end if;
  end loop;

  delete from public.orders where phone=regexp_replace(p_phone,'[^0-9]','','g');
  get diagnostics v_count = row_count;
  return v_count;
end;
$$;
grant execute on function public.delete_customer_by_phone(text) to authenticated;
